stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: harbor.trongduong.website/shopnow/user-service:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  image: docker:20-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  script:
    - docker info
    - docker build -t $DOCKER_IMAGE .
    - docker login -u shopnow -p ssfKOPOO549 https://harbor.trongduong.website/
    - docker push $DOCKER_IMAGE
  tags:
    - runner-shared-1

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl set image deployment/shopnow-user-service-deployment shopnow-user-service=$DOCKER_IMAGE -n shopnow
  tags:
    - runner-shared-1
